# Generated by Django 2.2.13 on 2021-07-10 08:46

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.URLField(blank=True, null=True, unique=True, verbose_name='Twitter web page')),
                ('facebook', models.URLField(blank=True, null=True, unique=True, verbose_name='Facebook web page')),
                ('instagram', models.URLField(blank=True, null=True, unique=True, verbose_name='Instagram web page')),
                ('skype', models.URLField(blank=True, null=True, unique=True, verbose_name='Skype web page')),
                ('linkedin', models.URLField(blank=True, null=True, unique=True, verbose_name='Linedin web page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('header_of_homepage', models.CharField(blank=True, max_length=300, verbose_name='متن عنوان اول صفحه اصلی')),
                ('header2_of_homepage', models.CharField(blank=True, max_length=300, verbose_name='متن عنوان دوم صفحه اصلی')),
                ('header_about', models.CharField(blank=True, max_length=300, verbose_name='عنوان درباره ما')),
                ('header_about_italic', models.CharField(blank=True, max_length=300, verbose_name='عنوان دوم درباره ما با فونت ایتالیک')),
                ('about_paragraph_check1', wagtail.core.fields.RichTextField(blank=True, max_length=2000, verbose_name='متن نکته اول قسمت درباره ما')),
                ('about_paragraph_check2', wagtail.core.fields.RichTextField(blank=True, max_length=2000, verbose_name='متن نکته دوم قسمت درباره ما')),
                ('about_paragraph_check3', wagtail.core.fields.RichTextField(blank=True, max_length=2000, verbose_name='متن نکته سوم قسمت درباره ما')),
                ('about_paragraph', wagtail.core.fields.RichTextField(blank=True, max_length=200, verbose_name='متن آخر قسمت درباره ما')),
                ('name_of_counter1', models.CharField(blank=True, max_length=30, verbose_name='کلمه اول شمارنده')),
                ('counter1', models.DecimalField(decimal_places=0, default=10, max_digits=4, verbose_name='عدد اول شمارنده')),
                ('name_of_counter2', models.CharField(blank=True, max_length=30, verbose_name='کلمه دوم شمارنده')),
                ('counter2', models.DecimalField(decimal_places=0, default=10, max_digits=4, verbose_name='عدد دوم شمارنده')),
                ('name_of_counter3', models.CharField(blank=True, max_length=30, verbose_name='کلمه سوم شمارنده')),
                ('counter3', models.DecimalField(decimal_places=0, default=10, max_digits=4, verbose_name='عدد سوم شمارنده')),
                ('name_of_counter4', models.CharField(blank=True, max_length=30, verbose_name='کلمه سوم شمارنده')),
                ('counter4', models.DecimalField(decimal_places=0, default=10, max_digits=4, verbose_name='عدد سوم شمارنده')),
                ('header_of_green_box', models.CharField(blank=True, max_length=300, verbose_name='عنوان باکس سبز بزرگ')),
                ('text_of_green_box', models.TextField(blank=True, max_length=500, verbose_name='متن باکس سبز بزرگ ')),
                ('header_of_box1', models.CharField(blank=True, max_length=300, verbose_name='عنوان باکس  سفید اول')),
                ('text_of_box1', models.TextField(blank=True, max_length=500, verbose_name='متن باکس سفید اول')),
                ('header_of_box2', models.CharField(blank=True, max_length=300, verbose_name='عنوان باکس سفید دوم')),
                ('text_of_box2', models.TextField(blank=True, max_length=500, verbose_name='متن باکس سفید دوم')),
                ('header_of_box3', models.CharField(blank=True, max_length=300, verbose_name='عنوان باکس سفید سوم')),
                ('text_of_box3', models.TextField(blank=True, max_length=500, verbose_name='متن باکس سفید سوم')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('img1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_about', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_client6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_cover1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_cover2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('img_cover3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
